
###Setup###
setwd("~/Lab/Primate Development/Data/Run 2")
#setwd("~/Documents/Primat-eDevelopment")
library("limma")
library("edgeR")
library("plyr")
library("ggplot2")
theme_set(theme_bw(base_size = 16))
library("biomaRt")
library("RColorBrewer")
library("VennDiagram")
library("gridExtra")
library("car")
library("topGO")
library("Cormotif")
library("ggfortify")
library(gplots)
library(statmod)
library(qtlcharts)
library(RColorBrewer)
library(ashr)
pal <- c(brewer.pal(9, "Set1"), brewer.pal(8, "Set2"), brewer.pal(12, "Set3"))
#library("ggbiplot")

###Make gene x sample matrix###
chimps <- read.table("chimp.fc.Mapping34.final.txt", header = TRUE)
chimps <- t(chimps)
humans <- read.table ("human.fc.Mapping34.final.txt", header = TRUE)
humans <- t(humans)
all(rownames(chimps) == rownames(humans)) #are they the same
both <- cbind(humans, chimps)
chimps_gene <- data.frame(chimps)
humans_gene <- data.frame(humans)
cmh <- colMeans(humans_gene)
cmc <- colMeans(chimps_gene)
mean(colMeans(humans_gene))
mean(colMeans(chimps_gene))
hist(cmh, breaks=100)
hist(cmc, breaks=100)
csh <- colSums(humans_gene)
csc <- colSums(chimps_gene)
hist(csh, breaks = 100)
hist(csc, breaks = 100)
mean (csh)
mean(csc)
barplot(csh)
sample_names <- colnames(both)
sample_names
write.table(sample_names, file = "samplenames.txt")

###Deal with technical factors###
sample_features <- read.table("samplefactors.txt", header=TRUE)
dim(sample_features)
rownames(sample_features) <- sample_names
rownames(sample_features)
#john_table <- rbind(sample_features[,7], sample_features[,2], both)
#write.table(john_table, sep="\t", file="john_table.txt")
both_minus <- both #if you remove nothing, cause call this later
#remove outlier
remove <- c(1)
sample_names[remove]
both_minus <- both[,-remove]
sample_features <- sample_features[-remove,]
sample_names <- sample_names[-remove]
dim(both_minus)
dim(sample_features)

batch <- sample_features[,3]
sex <- sample_features[,4]
day <- sample_features[,2]
RIN <- sample_features[,9]
line <- sample_features[,1]
mastermix <- sample_features[,10]
rnabatch <- sample_features[,6]
rnadate <- sample_features[,5]
class(day) <- "character"
species <- sample_features[,7]
samplenames <- sample_features[,8]
samplenames <- lapply(samplenames, as.character, stringsAsFactors=FALSE)
names_same <- cbind(sample_names, samplenames)
head(names_same) #won't be the same if you've removed samples

hist(rowSums(both), breaks=100)

bsh <- colSums(both_minus)
bsh2 <- cbind(bsh,species)
bsh2 <- bsh2[order(bsh2[,1]),] 
barplot(bsh2[,1], names=bsh2[,2])

###CPM transformation###
dat_cpm <- cpm(both_minus, log=TRUE)
#dat_cpm[mapply(is.infinite(dat_cpm))] <- -99999
dat_cpm[mapply(is.infinite, dat_cpm)] <- NA
#dat_cpm[!is.finite(dat_cpm)] <- NA
all(is.finite(dat_cpm))
hist(rowMeans(dat_cpm))
hist(rowSums(dat_cpm))
hist(dat_cpm)

###Remove lowly expressed genes ### WILL NEED TO ADJUST THIS SECTION DEPENDING ON REMOVED SAMPLES ####
#expr_genes <- rowMeans(dat_cpm)>-2
#length(expr_genes)
expr_genes <- (rowSums(dat_cpm[,1:31] > -2) > 10 & rowSums(dat_cpm[,32:63] > -2) > 10)
sum(expr_genes)
Number_expr_genes <- sum(expr_genes)
dat_cpm_trimmed <- dat_cpm [expr_genes,]
both_minus <- both_minus[expr_genes,]
both <- both[expr_genes,]
genesxsamples <- dim(dat_cpm_trimmed)
hist(dat_cpm_trimmed)
joyce_table <- rbind(sample_features[,7], sample_features[,2], both)
write.table(joyce_table, sep="\t", file="joyce_table.txt")

#dat_means <- rowMeans(dat_cpm_trimmed)
sarah <- t(apply(dat_cpm_trimmed, 1, scale, scale=FALSE, center=TRUE))
colnames(sarah) <- colnames(dat_cpm_trimmed)
sarah_table <- rbind(sample_features[,7], sample_features[,2], sarah)
write.table(sarah_table, sep="\t", file="sarah_table.txt")

###PCA###
pca <- prcomp(x = t(dat_cpm_trimmed), retx = TRUE, center = TRUE, scale = TRUE)
#plot_pca <- ggplot( mapping = aes(x = PC1, y = PC2,
#                                 col = time, size = control)) +
#  geom_point() +
#  scale_size_discrete(range = c(5, 2)) +
#  scale_color_brewer(palette = "Dark2")
#plot_pca <- plot(pca)
matrixpca <- pca$x
pc1 <- matrixpca[,1]
pc2 <- matrixpca[,2]
pc3 <- matrixpca[,3]
pc4 <- matrixpca[,4]
pc5 <- matrixpca[,5]

pcs <- data.frame(pc1, pc2, pc3, pc4, pc5)
summary <- summary(pca)
summary$PC1
summary$importance[2,1]*100),"% of variance", sep=" ")
xlab <- paste("PC!", summary$importance[2,1]*100, "% of variance")
xlab
ggplot(data=pcs, aes(x=pc1, y=pc2, color=day, shape=species, size=2)) +
geom_point() + xlab(paste("PC1", (summary$importance[2,1]*100), "% of variance")) + ylab(paste("PC2", (summary$importance[2,2]*100), "% of variance"))


ggplot(data=pcs, aes(x=pc2, y=pc3, color=day, shape=species, size=2)) +
geom_point() + xlab(paste("PC2", (summary$importance[2,2]*100), "% of variance")) + ylab(paste("PC3", (summary$importance[2,3]*100), "% of variance"))


plot(pca$x, col=day)
text(pca$x, labels=samplenames)
#plot(pca$x[,(2:3)], col=rnabatch)
#text(pca$x[,(2:3)], labels=samplenames)
#plot(pca$x[,(2:4)], col=rnabatch)
#text(pca$x[,(2:4)], labels=samplenames)

### Calculate Pairwise Correlations ###

pair_cor <- cor(dat_cpm_trimmed)
pair_cor <- as.data.frame(pair_cor)

###Heatmaps###
#Do correlation- can specify which type of correlation to perform
cors <- cor(dat_cpm_trimmed, method="spearman", use="pairwise.complete.obs")

#Set Labels for your axes
labels <- sample_names

#Nice to use so that previous formatting is reset
dev.off()

#Set pretty blue color for your heat map

colors <- colorRampPalette(c(brewer.pal(9, "Blues")[1],brewer.pal(9, "Blues")[9]))(100)

#Call the function (basic code)
heatmap.2(cors, scale="none", col = colors, margins = c(12, 12), trace='none', denscol="white")

#Fancy labeling and coloring 

heatmap.2( cors, scale="none", col = colors, margins = c(12, 12), trace='none', denscol="white", labCol=labels, ColSideColors=pal[as.integer(as.factor(BS_seq_info_two[ ,2]))], RowSideColors=pal[10:13][as.integer(as.factor(BS_seq_info_two[ ,3]))], cexCol = 1.5)

heatmap.2(dat_cpm_trimmed, scale="none", col = colors, margins = c(12, 12), trace='none', denscol="white", labCol=labels, ColSideColors=pal[as.integer(as.factor(BS_seq_info_two[ ,2]))], RowSideColors=pal[10:13][as.integer(as.factor(BS_seq_info_two[ ,3]))], cexCol = 1.5)

###CorMotiff###
# Create a factor for the experiments, with the levels ordered such that
# as.numeric converts them to numbers in a defined manner
group_fac <- factor(paste(species, day, sep = "."),
                    levels = c("C.0", "C.1", "C.2", "C.3",
                               "H.0", "H.1", "H.2", "H.3"))
groupid <- as.numeric(group_fac)
# Conditions to compare:
# day0, day1, day2, day3, 
compid_day <- data.frame(c1 = c(1, 2, 3, 4),
                         c2 = c(5, 6, 7, 8))
compid_tran <- data.frame(c1 = c(1, 2, 3, 5, 6, 7),
                          c2 = c(2, 3, 4, 6, 7, 8))
compid_all <- data.frame(c1 = c(1, 2, 3, 4, 1, 2, 3, 5, 6, 7),
                         c2 = c(5, 6, 7, 8, 2, 3, 4, 6, 7, 8))
                         
compid_chimp <- data.frame(c1=c(1,2,3), c2=c(2,3,4))                         
compid_human <- data.frame(c1=c(5,6,7), c2=c(6,7,8))

#interspecies differences at each day
set.seed(12345)
cormotif_day <- cormotiffit(exprs = dat_cpm_trimmed, groupid = groupid,
                        compid = compid_day, K = 3:5)
plotIC(cormotif_day)
plotMotif(cormotif_day)

gene_prob_day <- cormotif_day$bestmotif$p.post
rownames(gene_prob_day) <- rownames(dat_cpm_trimmed)

prob_sp_1 <- rownames(gene_prob_day[(gene_prob_day[,1] < 0.5 & gene_prob_day[,2] <0.5 & gene_prob_day[,3] <0.5 & gene_prob_day[,4] <0.5),])
length(prob_sp_1)

prob_sp_2 <- rownames(gene_prob_day[(gene_prob_day[,1] >0.9 & gene_prob_day[,2] >0.9 & gene_prob_day[,3] <0.5 & gene_prob_day[,4] <0.5),])
length(prob_sp_2)

prob_sp_3 <- rownames(gene_prob_day[(gene_prob_day[,1] >0.9 & gene_prob_day[,2] >0.9 & gene_prob_day[,3] > 0.9 & gene_prob_day[,4] > 0.9),])
length(prob_sp_3)

prob_sp_4 <- rownames(gene_prob_day[(gene_prob_day[,1] <0.5& gene_prob_day[,2] <0.5 & gene_prob_day[,3] <0.5 & gene_prob_day[,4] >0.9),])
length(prob_sp_4)

prob_sp_5 <- rownames(gene_prob_day[(gene_prob_day[,1] <0.5 & gene_prob_day[,2] <0.5 & gene_prob_day[,3] > 0.9 & gene_prob_day[,4] >0.9),])
length(prob_sp_5)

#differences during diffentiation
set.seed(12345)
cormotif_tran <- cormotiffit(exprs = dat_cpm_trimmed, groupid = groupid,
                        compid = compid_tran, K = 5:10)
plotIC(cormotif_tran)
plotMotif(cormotif_tran)

#combined interspecies and diffentiation differences
set.seed(12345)
cormotif_all <- cormotiffit(exprs = dat_cpm_trimmed, groupid = groupid,
                            compid = compid_all, K = 9:15)
                            
plotIC(cormotif_all)
plotMotif(cormotif_all)

#diff during diff sep species
set.seed(12345)
cormotif_chimp <- cormotiffit(exprs = dat_cpm_trimmed, groupid = groupid,
                            compid = compid_chimp, K = 9:15)
                            
plotIC(cormotif_chimp)
plotMotif(cormotif_chimp)

cormotif_human <- cormotiffit(exprs = dat_cpm_trimmed, groupid = groupid,
                            compid = compid_human, K = 9:15)
                            
gene_prob <- cormotif_human$bestmotif$p.post

plotIC(cormotif_human)
plotMotif(cormotif_human)

sessionInfo()
### Variance ###
day <- as.factor(day)
both <- dat_cpm_trimmed
#both_day <- rbind(both, day)
d0H <- both[,day=="0" & species=="H"]
dim(d0H)
d0C <- both[,day=="0" & species=="C"]
dim(d0C)

d1H <- both[,day=="1" & species=="H"]
dim(d1H)
d1C <- both[,day=="1" & species=="C"]
dim(d1C)


d2H <- both[,day=="2" & species=="H"]
dim(d2H)
d2C <- both[,day=="2" & species=="C"]
dim(d2C)


d3H <- both[,day=="3" & species=="H"]
dim(d3H)
d3C <- both[,day=="3" & species=="C"]
dim(d3C)


var_d0H <- apply(d0H, 1, var)
hist(var_d0H)
m0h <- mean(var_d0H)
var_d1H <- apply(d1H, 1, var)
hist(var_d1H)
m1h <- mean(var_d1H)
var_d2H <- apply(d2H, 1, var)
hist(var_d2H)
m2h <- mean(var_d2H)
var_d3H <- apply(d3H, 1, var)
hist(var_d3H)
m3h <- mean(var_d3H)

var_d0C <- apply(d0C, 1, var)
hist(var_d0C)
m0c <- mean(var_d0C)
var_d1C <- apply(d1C, 1, var)
hist(var_d1C)
m1c <- mean(var_d1C)
var_d2C <- apply(d2C, 1, var)
hist(var_d2C)
m2c <- mean(var_d2C)
var_d3C <- apply(d3C, 1, var)
hist(var_d3C)
m3c <- mean(var_d3C)

means <- c(m0h, m1h, m2h, m3h, m0c, m1c, m2c, m3c)
plot(means)
boxplot(var_d0H, var_d0C, var_d1H, var_d1C, var_d2H, var_d2C, var_d3H, var_d3C, ylim=c(0,4)) 

###Linear Model###
#for i in length()
#lmfit <- lm(dat_cpm_trimmed[i,] = species + day)


### Iplot ###

iplotCorr(substitute(dat_cpm_trimmed))
iplotCorr(as.character(expr))

### Ash ###


###Limma###
dim(both_minus)
species <- factor(species)
species <- relevel(species, ref="C") 
day <- factor(day)

#contrasts(species) <- contr.sum(2)
#contrasts(day) <- contr.sum(4)
design <- model.matrix(~species+day+species:day)
design

#cont_matrix<-makeContrasts(D1=(day1, D2=(day2), D3=(day3), levels=design)
y <- DGEList(both_minus)
y <- calcNormFactors(y)
v <- voom(y, design)
corfit <- duplicateCorrelation(both_minus,design,block=line)
fit <- lmFit(v, design, block=line, correlation=corfit$consensus)
#fit2 <- contrasts.fit(fit, cont_matrix)
fit2 <- eBayes(fit)
stats_list <- list()
pv_list <- fit2$p.value
output_all <- topTable(fit2, number=20000, sort.by="none")  
#output_all_1 <- topTable(fit2, coef="D1", number=20000, sort.by="none")
#output_all_2 <- topTable(fit2, coef="D2", number=20000, sort.by="none")
#output_all_3 <- topTable(fit2, coef="D3", number=20000, sort.by="none")
head(output_all)

Bspecies <- output_all$speciesC
Bspecies_chimpref <- Bspecies
Bspecies_humanref <- Bspecies

names(Bspecies) <- rownames(output_all)
Bspecies <- Bspecies[order(Bspecies)]
Pspecies <- pv_list[,2]
adjPspecies <- p.adjust(Pspecies, method = "BH")
sigspecies <- adjPspecies[adjPspecies < 0.05]
sigspecies <- sigspecies[order(sigspecies)]
sigspeciesnames <- names(sigspecies)
length(sigspecies)

BD1 <- output_all$day1
Chimp_ref_BD1 <- BD1
Human_ref_BD1 <- BD1
BD1_comp <- cbind(Chimp_ref_BD1, Human_ref_BD1)
cor(BD1_comp)
names(BD1) <- rownames(output_all)
BD1 <- BD1[order(BD1)]
PBD1 <- pv_list[,3]
adjPBD1 <- p.adjust(PBD1, method = "BH")
sigBD1 <- adjPBD1[adjPBD1 < 0.05]
sigBD1 <- sigBD1[order(sigBD1)]
sigBD1names <- names(sigBD1)
length(sigBD1)

BD2 <- output_all$day2
names(BD2) <- rownames(output_all)
BD2 <- BD2[order(BD2)]
PBD2 <- pv_list[,4]
adjPBD2 <- p.adjust(PBD2, method = "BH")
sigBD2 <- adjPBD2[adjPBD2 < 0.05]
sigBD2 <- sigBD2[order(sigBD2)]
sigBD2names <- names(sigBD2)
length(sigBD2)


BD3 <- output_all$day3
names(BD3) <- rownames(output_all)
BD3 <- BD3[order(BD3)]
PBD3 <- pv_list[,5]
adjPBD3 <- p.adjust(PBD3, method = "BH")
sigBD3 <- adjPBD1[adjPBD3 < 0.05]
sigBD3 <- sigBD3[order(sigBD3)]
sigBD3names <- names(sigBD3)
length(sigBD3)

BspeciesD1 <- output_all$speciesH.day1
names(BspeciesD1) <- rownames(output_all)
BspeciesD1 <- BspeciesD1[order(BspeciesD1)]
Pspecies1 <- pv_list[,6]
adjPspecies1 <- p.adjust(Pspecies1, method = "BH")
sigspecies1 <- adjPspecies1[adjPspecies1 < 0.05]
sigspecies1 <- sigspecies1[order(sigspecies1)]
sigspecies1names <- names(sigspecies1)
length(sigspecies1)

BspeciesD2 <- output_all$speciesH.day2
names(BspeciesD2) <- rownames(output_all)
BspeciesD2 <- BspeciesD2[order(BspeciesD2)]
Pspecies2 <- pv_list[,7]
adjPspecies2 <- p.adjust(Pspecies2, method = "BH")
sigspecies2 <- adjPspecies2[adjPspecies2 < 0.05]
sigspecies2 <- sigspecies2[order(sigspecies2)]
sigspecies2names <- names(sigspecies2)
length(sigspecies2)

BspeciesD3 <- output_all$speciesH.day3
names(BspeciesD3) <- rownames(output_all)
BspeciesD3 <- BspeciesD3[order(BspeciesD3)]
Pspecies3 <- pv_list[,8]
adjPspecies3 <- p.adjust(Pspecies3, method = "BH")
sigspecies3 <- adjPspecies3[adjPspecies3 < 0.05]
sigspecies3 <- sigspecies3[order(sigspecies3)]
sigspecies3names <- names(sigspecies3)
length(sigspecies3)


sig3 <- dat_cpm_trimmed[sigspecies3names,]
for (i in 1:10) {
play <- sig3[i,]
playdf <- data.frame(play,day,species)
#print(playdf)
print(ggplot(data=playdf, aes(x=day, y=play, fill=species)) + geom_boxplot(aes(fill=species)) + ggtitle(rownames(sig3)[i]) + ylab("expression"))
}
sig2 <- dat_cpm_trimmed[sigspecies2names,]
for (i in 1:10) {
play <- sig2[i,]
playdf <- data.frame(play,day,species)
#print(playdf)
print(ggplot(data=playdf, aes(x=day, y=play, fill=species)) + geom_boxplot(aes(fill=species)) + ggtitle(rownames(sig2)[i])+ ylab("expression"))
}
sig1 <- dat_cpm_trimmed[sigspecies1names,]
for (i in 1:10) {
play <- sig1[i,]
playdf <- data.frame(play,day,species)
#print(playdf)
print(ggplot(data=playdf, aes(x=day, y=play, fill=species)) + geom_boxplot(aes(fill=species)) + ggtitle(rownames(sig1)[i])+ ylab("expression"))
}

sigspecies <- dat_cpm_trimmed[sigspeciesnames,]
for (i in 1:10) {
play <- sigspecies[i,]
playdf <- data.frame(play,day,species)
#print(playdf)
print(ggplot(data=playdf, aes(x=day, y=play, fill=species)) + geom_boxplot(aes(fill=species)) + ggtitle(rownames(sigspecies)[i])+ ylab("expression"))
}

sigD3 <- dat_cpm_trimmed[sigBD1names,]
for (i in 1:10) {
play <- sigD3[i,]
playdf <- data.frame(play,day,species)
#print(playdf)
print(ggplot(data=playdf, aes(x=day, y=play, fill=species)) + geom_boxplot(aes(fill=species)) + ggtitle(rownames(sigD3)[i])+ ylab("expression"))
}
sigD2 <- dat_cpm_trimmed[sigBD2names,]
for (i in 1:10) {
play <- sigD2[i,]
playdf <- data.frame(play,day,species)
#print(playdf)
print(ggplot(data=playdf, aes(x=day, y=play, fill=species)) + geom_boxplot(aes(fill=species)) + ggtitle(rownames(sigD2)[i])+ ylab("expression"))
}
sigD1 <- dat_cpm_trimmed[sigBD1names,]
for (i in 1:10) {
play <- sigD1[i,]
playdf <- data.frame(play,day,species)
#print(playdf)
print(ggplot(data=playdf, aes(x=day, y=play, fill=species)) + geom_boxplot(aes(fill=species)) + ggtitle(rownames(sigD1)[i])+ ylab("expression"))
}

venn(list(d1=sigBD1names, d2=sigBD2names, d3=sigBD3names))
venn(list(spd1=sigspecies1names, spd2=sigspecies2names, spd3=sigspecies3names))
par(mfrow = c(1,3)) 
venn(list(spd1=sigspecies1names, d1=sigBD1names))
venn(list(spd2=sigspecies2names, d2=sigBD2names))
venn(list(spd3=sigspecies3names, d3=sigBD2names))

par(mfrow = c(1,1)) 
length_days <- c(length(sigBD1names), length(sigBD2names), length(sigBD3names))
length_intrxn <- c(length(sigspecies1names), length(sigspecies2names), length(sigspecies3names))
meets1 <- 
length_both <- rbind(length_days, length_intrxn)
colnames(length_both)<- c("day 1", "day2", "day3")
barplot(length_both, col=c("darkblue", "red"), legend=rownames(length_both))

Betas <- cbind(Bspecies, BD1, BD2, BD3, BspeciesD1, BspeciesD2, BspeciesD3)
head(Betas)
rownames(Betas) <- rownames(output_all)
rownames(Betas)
heatmap(Betas)
hist(Bspecies)
hist(BD1)
hist(BD2)
hist(BD3)
hist(BspeciesD1)
hist(BspeciesD2)
hist(BspeciesD3)

for (coef in colnames(cont_matrix)) {
  stats_list[[coef]] <- topTable(fit2, coef = coef, number = nrow(counts),
                                 sort.by = "none")
}
stats_list <- llply(stats_list, function(x) cbind(gene = rownames(x), x))
stats <- ldply(stats_list, .id = "test")
stats$gene <- as.character(stats$gene)


#design <- model.matrix(~0+ mymodel)
#colnames(design) <- levels(mymodel)
#mymodel <- data.frame(day,species)
m <- factor(paste(species, day, sep="."))
m
species
design <- model.matrix(~ 0+m)
#colnames(design) <- levels(m)
design

corfit <- duplicateCorrelation(both_minus,design,block=line)

cont_matrix<-makeContrasts(D0=mH.0-mC.0, D1 = mH.1-mC.1, D2 = mH.2-mC.2, D3 = mH.3-mC.3, levels=design)

y <- DGEList(both_minus)
y <- calcNormFactors(y)
v <- voom(y, design)
fit <- lmFit(v, design, block=line, correlation=corfit$consensus)
fit2 <- contrasts.fit(fit, cont_matrix)
fit2 <- eBayes(fit2)
stats_list <- list()
pv_list <- fit2$p.value

output_all_0 <- topTable(fit2, coef="D0", number=20000, sort.by="none")
output_all_1 <- topTable(fit2, coef="D1", number=20000, sort.by="none")
output_all_2 <- topTable(fit2, coef="D2", number=20000, sort.by="none")
output_all_3 <- topTable(fit2, coef="D3", number=20000, sort.by="none")
head(output_all_0)

dfs <- data.frame(output_all_0$logFC, output_all_1$logFC, output_all_2$logFC, output_all_3$logFC)
dfs <- stack(dfs)
head(dfs)
plot(density((FC_all)))

ggplot(dfs, aes(x=values)) + geom_density(aes(group=ind, color=ind))


plot(density(output_all_3$logFC), density(output_all_2$logFC))
ggplot(data=pcs, aes(x=pc2, y=pc3, color=day, shape=species, size=2)) +
geom_density(mapping = NULL, data = NULL, stat = "density", position = "identity", ..., na.rm = FALSE, show.legend = NA, inherit.aes = TRUE)

###Find Not significant genes###
notsig0 <- output_all_0[(output_all_0$adj.P.Val)>0.01,]
head(notsig0)
dim(notsig0)
notsig1 <- output_all_1[(output_all_1$adj.P.Val)>0.01,]
notsig2 <- output_all_2[(output_all_2$adj.P.Val)>0.01,]
notsig3 <- output_all_3[(output_all_3$adj.P.Val)>0.01,]
dim(notsig1)
dim(notsig2)
dim(notsig3)
notsig_any <- intersect(intersect(intersect(rownames(notsig0), rownames(notsig1)), rownames(notsig2)), rownames(notsig3))
Number_notsig <- length(notsig_any)

#pv_list_raw <- output_all[,4, drop=FALSE]
#pv_list_adj <- output_all[,5, drop=FALSE]

output_D0 <- topTable(fit2, coef = "D0", number=20000, p.value=.01) #default adjust method is BH
output_D1 <- topTable(fit2, coef = "D1", number=20000, p.value=.01) 
output_D2 <- topTable(fit2, coef = "D2", number=20000, p.value=.01) 
output_D3 <- topTable(fit2, coef = "D3", number=20000, p.value=.01) 

output_D0 <- output_all_0[(output_all_0$adj.P.Val)<0.01,]
output_D1 <- output_all_1[(output_all_1$adj.P.Val)<0.01,]
output_D2 <- output_all_2[(output_all_2$adj.P.Val)<0.01,] 
output_D3 <- output_all_3[(output_all_3$adj.P.Val)<0.01,]

mean_effect_D0 <- mean(output_all_0$logFC)
mean_effect_D1 <- mean(output_all_1$logFC)
mean_effect_D2 <- mean(output_all_2$logFC)
mean_effect_D3 <- mean(output_all_3$logFC)

mean_effects <- c(mean_effect_D0, mean_effect_D1, mean_effect_D2, mean_effect_D3)
plot(mean_effects)

head(output_D0)
length(output_D0$adj.P.Val)
head(output_D1)
length(output_D1$adj.P.Val)
head(output_D2)
length(output_D2$adj.P.Val)
head(output_D3)
length(output_D3$adj.P.Val)

#Find significant genes

sig_d0 <- rownames(output_D0)
sig_d1 <- rownames(output_D1)
sig_d2 <- rownames(output_D2)
sig_d3 <- rownames(output_D3)

par(mfrow=c(1,1))
venn(list(sig0 = sig_d0, sig1= sig_d1, sig2=sig_d2, sig3=sig_d3))

Number_d0 <- length(sig_d0)
Number_d1 <- length(sig_d1)
Number_d2 <- length(sig_d2)
Number_d3 <- length(sig_d3)

#Find significant genes only in one day
sig_d1_only <- sig_d1[!(sig_d1 %in% sig_d0)]
sig_d1_only <- sig_d1_only[!(sig_d1_only %in% sig_d2)]
sig_d1_only <- sig_d1_only[!(sig_d1_only %in% sig_d3)]

#Find significant genes only in one day
sig_d3_only <- sig_d3[!(sig_d3 %in% sig_d0)]
sig_d3_only <- sig_d3_only[!(sig_d3_only %in% sig_d2)]
sig_d3_only <- sig_d3_only[!(sig_d3_only %in% sig_d1)]

#Find significant genes only in one day
sig_d0_only <- sig_d0[!(sig_d0 %in% sig_d1)]
sig_d0_only <- sig_d0_only[!(sig_d0_only %in% sig_d2)]
sig_d0_only <- sig_d0_only[!(sig_d0_only %in% sig_d3)]

#Find significant genes only in one day
sig_d2_only <- sig_d2[!(sig_d2 %in% sig_d0)]
sig_d2_only <- sig_d2_only[!(sig_d2_only %in% sig_d3)]
sig_d2_only <- sig_d2_only[!(sig_d2_only %in% sig_d1)]

#Find significant genes in all days
sig_all <- sig_d2[(sig_d2 %in% sig_d0)]
length(sig_all)
sig_all <- sig_all[(sig_all %in% sig_d3)]
length(sig_all)
sig_all <- sig_all[(sig_all %in% sig_d1)]

#Find significant genes arising at a given day
sig_d0_arise <- sig_d0

sig_d1_arise <- sig_d1[!(sig_d1 %in% sig_d0)]

sig_d2_arise <- sig_d2[!(sig_d2 %in% sig_d0)]
sig_d2_arise <- sig_d2_arise[!(sig_d2_arise %in% sig_d1)]

sig_d3_arise <- sig_d3_only

dfs <- data.frame(output_D0$logFC, output_D1$logFC, output_D2$logFC, output_D3$logFC)
dfs <- stack(dfs)
head(dfs)
plot(density((FC_all)))

ggplot(dfs, aes(x=values)) + geom_density(aes(group=ind, color=ind))

#result <- decideTests(fit2)
#result

###Plot nonsignificant genes###
notsig <- dat_cpm_trimmed[notsig_any,]
#notsig <- data.frame(notsig)
dim(notsig)
head(notsig)
notsigex <- notsig[rowMeans(notsig)>2,]
dim(notsigex)
#notsighc <- cbind(rowMeans(notsig[,1:19]), rowMeans(notsig[,20:43]))
#colnames(notsighc) <- c("Human", "Chimp")
#head(notsighc)
for (i in 30:50) {
play <- notsigex[i,]
playdf <- data.frame(play,day,species)
print(playdf)
print(ggplot(data=playdf, aes(x=day, y=play, fill=species)) + geom_boxplot(aes(fill=species)) + ggtitle(rownames(notsigex)[i]))
}

###Plot significant genes###
sig0 <- dat_cpm_trimmed[sig_d0,]
sig1 <- dat_cpm_trimmed[sig_d1,]
sig2 <- dat_cpm_trimmed[sig_d2,]
sig3 <- dat_cpm_trimmed[sig_d3,]

sig0ex <- sig0[rowMeans(sig0)>2,]
for (i in 1:10) {
play <- sig0ex[i,]
playdf <- data.frame(play,day,species)
print(playdf)
print(ggplot(data=playdf, aes(x=day, y=play, fill=species)) + geom_boxplot(aes(fill=species)) + ggtitle(rownames(sig0ex)[i]))
}

sig1_only <- dat_cpm_trimmed[sig_d1_only,]
sig1ex <- sig1_only[rowMeans(sig1_only)>2,]
for (i in 1:10) {
play <- sig1ex[i,]
playdf <- data.frame(play,day,species)
print(playdf)
print(ggplot(data=playdf, aes(x=day, y=play, fill=species)) + geom_boxplot(aes(fill=species)) + ggtitle(rownames(sig1ex)[i]))
}

sig3_only <- dat_cpm_trimmed[sig_d3_only,]
sig3ex <- sig3_only[rowMeans(sig3_only)>2,]
for (i in 10:20) {
play <- sig3ex[i,]
playdf <- data.frame(play,day,species)
#print(playdf)
print(ggplot(data=playdf, aes(x=day, y=play, fill=species)) + geom_boxplot(aes(fill=species)) + ggtitle(rownames(sig3ex)[i]))
}

sig_all_dat <- dat_cpm_trimmed[sig_all,]
sig_all_ex <- sig_all_dat[rowMeans(sig_all_dat)>2,]
for (i in 1:20) {
play <- sig_all_ex[i,]
playdf <- data.frame(play,day,species)
print(playdf)
print(ggplot(data=playdf, aes(x=day, y=play, fill=species)) + geom_boxplot(aes(fill=species)) + ggtitle(rownames(sig_all_x)[i]))
}
for (i in 1:20) {
play <- sig_all_ex[i,]
playdf <- data.frame(play,day,species)
print(playdf)
print(ggplot(data=playdf, aes(x=day, y=play, fill=species)) + geom_boxplot(aes(fill=species)) + ggtitle(rownames(sig_all_ex)[i]))
}
head(playdf)

###Specific Genes###
expr_foxp2 <- dat_cpm_trimmed["ENSG00000128573", ]
foxp2 <- data.frame(expr_foxp2,day,species)
ggplot(data=foxp2, aes(x=day, y=expr_foxp2, fill=species)) + geom_boxplot(aes(fill=species)) + ggtitle("FOXP2")

nrxn<- dat_cpm_trimmed["ENSG00000179915", ]
nrxndf<- data.frame(nrxn,day,species)
ggplot(data=nrxndf, aes(x=day, y=nrxn, fill=species)) + geom_boxplot(aes(fill=species)) + ggtitle("NRXN1")

pdx1<- dat_cpm_trimmed["ENSG00000164736", ]
pdx1df<- data.frame(pdx1,day,species)
ggplot(data=pdx1df, aes(x=day, y=pdx1, fill=species)) + geom_boxplot(aes(fill=species)) + ggtitle("PDX1")

sox2<- dat_cpm_trimmed["ENSG00000163508", ]
sox2df<- data.frame(sox2,day,species)
ggplot(data=sox2df, aes(x=day, y=sox2, fill=species)) + geom_boxplot(aes(fill=species)) + ggtitle("EOMES")

sox2<- dat_cpm_trimmed["ENSG00000121966", ]
sox2df<- data.frame(sox2,day,species)
ggplot(data=sox2df, aes(x=day, y=sox2, fill=species)) + geom_boxplot(aes(fill=species)) + ggtitle("CXCR4")

sox2<- dat_cpm_trimmed["ENSG00000157404", ]
sox2df<- data.frame(sox2,day,species)
ggplot(data=sox2df, aes(x=day, y=sox2, fill=species)) + geom_boxplot(aes(fill=species)) + ggtitle("ckit")

###Values###
Number_notsig #844
Number_d0 #2811
Number_d1 #1486
Number_d2 #1928
Number_d3 #2328
genesxsamples #14946 x 43

sig_day0 <- Number_d0 #2811
sig_day1 <- Number_d1 #1486
sig_day2 <- Number_d2 #1928
sig_day3 <- Number_d3 #2328
always_sig <- length(sig_all)


collect_total <- c(sig_day0, sig_day1, sig_day2, sig_day3, Number_notsig, always_sig)
plot(collect_total, xaxt="n", xlab="day", ylab="number significant", main="Total Genes Significant in Each Day")
axis(side=1, at=1:6, labels=c("sig_d0_total", "sig_d1_total", "sig_d2_total", "sig_d3_total", "never_sig", "always_sig"))



sig_day0_only <- length(sig_d0_only)
sig_day1_only <- length(sig_d1_only)
sig_day2_only <- length(sig_d2_only)
sig_day3_only <- length(sig_d3_only)

length(sig_all)

collect_only <- c(length(sig_d0_only), length(sig_d1_only), length(sig_d2_only), length(sig_d3_only))
plot(collect_only, xaxt="n", xlab="day", ylab="number significant", main="Genes Significant Only in One Day")
axis(side=1, at=1:4, labels=c("sig_d0_only", "sig_d1_only", "sig_d2_only", "sig_d3_only"))

length(sig_d0_arise)
length(sig_d1_arise)
length(sig_d2_arise)
length(sig_d3_arise)

collect_arise <- c(length(sig_d0_arise), length(sig_d1_arise), length(sig_d2_arise), length(sig_d3_arise))

plot(collect_arise, xaxt="n", xlab="day", ylab="number significant", main=" Significant Genes Arising by Day")
axis(side=1, at=1:4, labels=c("sig_d0_arise", "sig_d1_arise", "sig_d2_arise", "sig_d3_arise"))

plot(mean_effects, xaxt="n", xlab="day", ylab="mean effect size", main=" Effect Size by Day", pch=16)
axis(side=1, at=1:4, labels=c("Day 0", "Day 1", "Day 2", "Day 3"))


means <- c(m0h, m0c, m1h, m1c, m2h, m2c, m3h,m3c)
plot(means, xaxt="n", ylab="mean variance", xlab="timepoint",pch=16, bg="blue", col=c("cadetblue4", "hotpink", "cadetblue4", "hotpink", "cadetblue4", "hotpink", "cadetblue4", "hotpink"), main="Variance by Day")
axis(side=1, at=c(1.5, 3.5, 5.5, 7.5), labels=c("Day 0", "Day 1", "Day 2", "Day 3"))
 
legend(7,1, c("human", "chimp"), col = c("cadetblue4", "hotpink"),
       text.col = c("cadetblue4", "hotpink"),  pch = c(16,16),
       merge = TRUE, bg = "gray90")

boxplot(var_d0H, var_d0C, var_d1H, var_d1C, var_d2H, var_d2C, var_d3H, var_d3C, ylim=c(0,4))
#table of all
all_genes <- rownames(dat_cpm_trimmed)
n <- max(length(sigBD1names), length(sigBD2names), length(sigBD3names), length(sigspeciesnames), length(sigspecies1names), length(sigspecies2names), length(sigspecies3names), length(all_genes))
length(sigBD1names) <- n                      
length(sigBD2names) <- n
length(sigBD3names) <- n
length(sigspeciesnames) <- n
length(sigspecies1names) <- n
length(sigspecies2names) <- n
length(sigspecies3names) <- n
length(all_genes) <- n

n <- max(length(sigBD1names), length(sigBD2names), length(sigBD3names), length(sigspeciesnames), length(sigspecies1names), length(sigspecies2names), length(sigspecies3names), length(all_genes))
n2 <- max(length(sig_d0), length(sig_d1), length(sig_d2), length(sig_d3), length(sig_all), length(notsig_any))
length(sigBD1names) <- n                      
length(sigBD2names) <- n
length(sigBD3names) <- n
length(sigspeciesnames) <- n
length(sigspecies1names) <- n
length(sigspecies2names) <- n
length(sigspecies3names) <- n
length(all_genes) <- n
length(sig_d0) <- n2
length(sig_d1) <- n2
length(sig_d2) <- n2
length(sig_d3) <- n2
length(sig_all) <- n2
length(notsig_any) <- n2

sig_collect2 <- cbind(sig_d0, sig_d1, sig_d2, sig_d3, sig_all, notsig_any)
write.csv(sig_collect2, file="sigcollect2.txt")
write.csv(all_genes, file="all_genes.txt", row.names=FALSE)
sig_collect <- cbind(sigBD1names, sigBD2names, sigBD3names, sigspeciesnames, sigspecies1names, sigspecies2names, sigspecies3names, all_genes)
write.csv(sig_collect, file="sigcollect.txt")

sig_collect_arise <- cbind(sig_d0_arise, sig_d1_arise, sig_d2_arise, sig_d3_arise)
write.csv (sig_collect_arise, file="sig_arise.txt")

sig_collect_only <- cbind(sig_d0_only, sig_d1_only, sig_d2_only, sig_d3_only)
write.csv(sig_collect_only, file="sig_only.txt")
